name: Bug Report
description: Report bugs or issues.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! The more info you provide, the more we can help you.

  - type: checkboxes
    attributes:
      label: Check existing issues
      description: By submitting this issue, you checked there isn't [already an issue](https://github.com/ponder-sh/ponder/issues) for this bug.
      options:
        - label: I checked there isn't [already an issue](https://github.com/ponder-sh/ponder/issues) for the bug I encountered.
          required: true

  - type: input
    attributes:
      label: Ponder Version
      description: What version of Ponder are you using?
      placeholder: x.y.z (do not write `latest`)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps or code snippets to reproduce the behavior (`ponder.config.ts`, `ponder.schema.ts`, indexing functions, abi, etc).
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Logs? Screenshots? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false